import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bomba Landeta',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className,"bg-green-950"}>
        <nav className="bg-green-950 dark:bg-green-950 sticky w-full z-20 top-0 left-0 ">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-center mx-auto p-4">
            <Link href="https://flowbite.com/" className="flex items-center mx-px-1">
              <Image width={50} height={50} src="/images/logo_blanco.png" className="" alt="Flowbite Logo" />
            </Link>
            <h1 className='text-white mx-8'>Bomba José Maria Landeta</h1>
          </div>
        </nav>
        {children}
        {/* <script src=' ./node_modules/flowbite/dist/flowbite.min.js'></script>  */}
      </body>
    </html>
  )
}
